// Sample trainers data (photo placeholder reserved for later)
export const TRAINERS_INITIAL_DATA = [
  {
    id: 1,
    name: 'Sarah Chen',
    specialty: 'HIIT & Cardio',
    email: 'sarah.chen@primezone.com',
    phone: '+1 (555) 201-3401',
    programsCount: 2,
    status: 'Active',
    bio: 'Certified HIIT instructor with 8+ years experience. Passionate about helping members build endurance and confidence.',
  },
  {
    id: 2,
    name: 'Marcus Rivera',
    specialty: 'Yoga & Flexibility',
    email: 'marcus.rivera@primezone.com',
    phone: '+1 (555) 201-3402',
    programsCount: 1,
    status: 'Active',
    bio: 'RYT-500 yoga teacher. Specializes in vinyasa flow and restorative practices for all levels.',
  },
  {
    id: 3,
    name: 'Jake Wilson',
    specialty: 'Strength & Conditioning',
    email: 'jake.wilson@primezone.com',
    phone: '+1 (555) 201-3403',
    programsCount: 1,
    status: 'Active',
    bio: 'Former competitive powerlifter. Focus on compound lifts, form, and sustainable strength gains.',
  },
  {
    id: 4,
    name: 'Emma Lee',
    specialty: 'Pilates & Core',
    email: 'emma.lee@primezone.com',
    phone: '+1 (555) 201-3404',
    programsCount: 1,
    status: 'Active',
    bio: 'Pilates instructor certified in mat and reformer. Believes in core strength as the foundation of movement.',
  },
  {
    id: 5,
    name: 'Alex Torres',
    specialty: 'CrossFit & Functional',
    email: 'alex.torres@primezone.com',
    phone: '+1 (555) 201-3405',
    programsCount: 0,
    status: 'Active',
    bio: 'CrossFit L2 trainer. Loves coaching athletes of all levels through functional fitness and community.',
  },
]
